SELECT * FROM EMP;
-- 전체 평균 급여보다 많은 급여를 받는 사원들의 이름과 급여를 조회하라.
SELECT AVG(SAL) FROM EMP;
SELECT * FROM EMP WHERE SAL>2073.214285714285714285714285714285714286;

SELECT *
    FROM EMP
    WHERE SAL>(SELECT AVG(SAL) FROM EMP);

-- 이름이 'JONES'인 사원과 동일한 직무를 가진 사원을 조회하라.
SELECT JOB FROM EMP WHERE ENAME='JONES';
SELECT * FROM EMP WHERE JOB='MANAGER';
SELECT *
    FROM EMP
    WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='JONES');
-- 20번 부서에서 근무하는 사원과 +동일한 급여를 받는 사원들의 이름과 급여를 조회하라.
(SELECT DISTINCT SAL FROM EMP WHERE DEPTNO=30);
-- 2975.00, 3000.00, 1100.00 , 800.00
-- 2850.00, 1500.00, 950.00, 1250.00, 1600.00
SELECT * FROM EMP WHERE SAL IN (2850.00, 1500.00, 950.00, 1250.00, 1600.00);
SELECT *
    FROM EMP
    WHERE SAL IN (SELECT SAL FROM EMP WHERE DEPTNO=20);
-- 30번 부서 사원 중 한명이라도 급여가 더 높은 ...사원들을 조회하라.
SELECT SAL FROM EMP WHERE DEPTNO=30;
SELECT *
    FROM EMP
    WHERE SAL > SOME (SELECT SAL FROM EMP WHERE DEPTNO=30);

-- 10번 부서 사원 전원보다 급여가 높은 사원을 조회하라.
SELECT *
    FROM EMP
    WHERE SAL > ALL (SELECT SAL FROM EMP WHERE DEPTNO=10);

-- 20번 부서의 (직무, 급여) 조합과 같은 조건을 가진 사원들을 조회하라.
SELECT JOB,SAL FROM EMP WHERE DEPTNO=20;

SELECT *
    FROM EMP
    WHERE (JOB='MANAGER' AND SAL=2975 ) OR (JOB='ANALYST' AND SAL=3000);
SELECT *
    FROM EMP
    WHERE (JOB, SAL) IN (SELECT JOB,SAL FROM EMP WHERE DEPTNO=20);
-- 각 부서별 최고 급여를 받는 사원 정보를 조회하라.
SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO;
SELECT * FROM EMP
         WHERE DEPTNO=10 AND SAL=5000 OR
               DEPTNO=20 AND SAL=3000 OR
               DEPTNO=30 AND SAL=2850;
SELECT * FROM EMP
    WHERE (DEPTNO,SAL) IN(
        SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO
        );
-- 자기 부서의 평균 급여보다 높은 급여를 받는 사원들의 이름, 부서번호, 급여를 조회하라.
SELECT *
    FROM EMP e
    WHERE SAL>(SELECT AVG(a.SAL) FROM EMP a WHERE a.DEPTNO=e.DEPTNO);

SELECT DEPTNO,AVG(SAL) FROM EMP GROUP BY DEPTNO;
-- 서브쿼리 JOIN
SELECT *
    FROM EMP INNER JOIN
         (SELECT DEPTNO,AVG(SAL) avg FROM EMP GROUP BY DEPTNO) a
    ON EMP.DEPTNO=a.DEPTNO
    WHERE EMP.SAL > a.avg
    ORDER BY EMP.EMPNO;
-- 사원이 존재하는 부서만 조회하라.
    SELECT * FROM DEPT;
    SELECT DISTINCT DEPTNO FROM EMP;
    SELECT * FROM DEPT WHERE DEPTNO IN (SELECT DISTINCT DEPTNO FROM EMP);
    SELECT * FROM EMP WHERE DEPTNO=40;

SELECT *
    FROM DEPT
    WHERE EXISTS(SELECT * FROM EMP WHERE EMP.DEPTNO=DEPT.DEPTNO);

-- 각 사원의 이름, 급여와 함께 해당 사원 부서의 평균 급여를 같이 출력하라.
SELECT
    e.ENAME,
    e.SAL,
    e.DEPTNO,
    (SELECT AVG(d.SAL) FROM EMP d WHERE d.DEPTNO=e.DEPTNO) 부서별평균
    FROM EMP e;

-- over : 집계를 따로진행해서 기존출력에 더한다.

-- SELECT e.ENAME, e.SAL AVG(e.SAL) FROM EMP e;
SELECT e.ENAME, e.SAL, AVG(e.SAL) OVER() FROM EMP e;
SELECT z.이름,z.급여,z.부서번호,z.부서별평균 FROM (SELECT
       e.ENAME 이름,
       e.SAL 급여,
       e.DEPTNO 부서번호,
       AVG(e.SAL) OVER(partition by DEPTNO) 부서별평균
FROM EMP e) z
WHERE z.부서별평균>2500;


